import Image from 'next/image';
import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, Check, Sparkles } from 'lucide-react';
import { productBySlug, products } from '@/data/products';
import { Reveal } from '@/components/motion';

export function generateStaticParams(){ return products.map(p => ({ slug: p.slug })); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const p=productBySlug(slug); return p ? { title:p.name, description:p.description, openGraph:{title:`${p.name} | OGE-ACTRA TECH`,description:p.description,images:[p.image]} } : {}; }
export default async function Product({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const p=productBySlug(slug); if(!p) notFound(); return <>
<section className={`product-detail-hero product-detail-${p.accent}`}><div className="page-shell"><Link href="/products" className="inline-flex items-center gap-2 text-sm font-semibold text-cyan hover:text-white">← Back to product ecosystem</Link><div className="mt-10 grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><p className="eyebrow">{p.category}</p><h1 className="mt-4 text-6xl font-black tracking-[-.055em] md:text-8xl">{p.name}</h1><p className="mt-4 text-sm font-bold uppercase tracking-[.18em] text-purple">{p.status}</p><p className="mt-7 max-w-3xl text-xl leading-9 text-silver">{p.long}</p><Link href="/contact" className="btn-primary mt-8 px-7 py-4">Talk to OGE-ACTRA TECH <ArrowRight size={17}/></Link></Reveal><Reveal delay={.1}><div className="product-detail-image"><Image src={p.image} alt={`${p.name} visual`} fill priority sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover"/><div className="product-detail-overlay"/><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.24em] text-silver">Product within</p><p className="mt-1 font-black">OGE-ACTRA TECH</p></div><Sparkles className="text-cyan" size={22}/></div></div></Reveal></div></div></section>
<section className="px-5 pb-24"><div className="mx-auto max-w-7xl"><Reveal><p className="eyebrow">Capabilities</p><h2 className="mt-3 text-4xl font-black md:text-5xl">Built around a clear product mission.</h2></Reveal><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{p.features.map((f,i)=><Reveal key={f} delay={i*.04}><div className="prose-card flex gap-3"><Check className="mt-1 shrink-0 text-cyan" size={18}/><span className="font-semibold">{f}</span></div></Reveal>)}</div><div className="mt-16 grid gap-8 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow">What it enables</p><div className="mt-6 grid gap-3">{p.outcomes.map(o=><div key={o} className="rounded-2xl border border-white/8 bg-white/[.025] p-4 text-silver">{o}</div>)}</div></div><aside className="glass rounded-[2rem] p-8"><p className="eyebrow">Parent company</p><h2 className="mt-3 text-3xl font-black">OGE-ACTRA TECH</h2><p className="mt-4 leading-7 text-silver">{p.name} is a product within the OGE-ACTRA TECH technology portfolio. The parent company remains the technology brand across the ecosystem.</p></aside></div></div></section></>; }
