import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Brain, Code2, Globe2, Layers, Sparkles, Clapperboard, Boxes, Workflow, Database, GraduationCap, ShoppingBag } from 'lucide-react';
import { products } from '@/data/products';
import { Logo } from '@/components/Logo';
import { Reveal } from '@/components/motion';
import { ProductCard } from '@/components/ProductCard';
import { Ecosystem } from '@/components/Ecosystem';

const focus = [
 { title:'AI', copy:'Intelligent systems designed to augment creativity, decision-making and human potential.', icon:Brain },
 { title:'Software Engineering', copy:'Scalable product architecture and infrastructure built around real-world problems.', icon:Code2 },
 { title:'Digital Platforms', copy:'Connected products that help people create, learn, trade, compete and connect.', icon:Globe2 },
];
const industries = [
 ['Entertainment',Clapperboard],['Education',GraduationCap],['Commerce',ShoppingBag],['Creator Economy',Sparkles],['Digital Communities',Globe2],['Artificial Intelligence',Brain],['Emerging Technology',Boxes],
];

export default function Home(){return <>
 <section className="hero">
  <div className="grid-bg absolute inset-0"/><div className="hero-glow"/><div className="hero-scanline"/>
  <div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.04fr_.96fr]">
   <Reveal><div className="hero-brandline"><span className="hero-brand-dot"/> OGE-ACTRA TECH / TECHNOLOGY GROUP</div><p className="eyebrow mt-7">AI • SOFTWARE ENGINEERING • DIGITAL PLATFORMS</p><h1 className="mt-5 max-w-4xl text-5xl font-black tracking-[-.055em] md:text-7xl lg:text-[5.7rem] lg:leading-[.96]">Building the Technology <span className="gradient-text">Behind Tomorrow.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-silver">OGE-ACTRA TECH builds intelligent software, AI systems and digital platforms designed to transform how people create, learn, trade and connect.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary focus-ring px-7 py-4" href="/products">Explore Our Products <ArrowRight size={17}/></Link><Link className="focus-ring rounded-full border border-white/15 px-7 py-4 font-bold text-platinum transition hover:bg-white/[.06]" href="/company">About OGE-ACTRA TECH</Link></div><div className="hero-stats" aria-label="Company focus"><div><strong>04</strong><span>Digital products</span></div><div><strong>03</strong><span>Core capabilities</span></div><div><strong>01</strong><span>Technology company</span></div></div></Reveal>
   <Reveal delay={.1}><div className="hero-visual"><div className="hero-visual-top"><span>CORE SYSTEM</span><span>ONLINE / BUILDING</span></div><div className="hero-orb"/><span className="hero-particle hero-p1"/><span className="hero-particle hero-p2"/><span className="hero-particle hero-p3"/><span className="hero-particle hero-p4"/><div className="hero-data hd1">AI / 001</div><div className="hero-data hd2">PLATFORM / 004</div><div className="hero-data hd3">SYSTEM / 24</div><div className="hero-core"><span className="core-ring"/><div className="core-badge"><Logo/></div><p className="relative mt-6 text-xs uppercase tracking-[.28em] text-silver">Technology company<br/>powering multiple products</p></div><div className="hero-label"><span>AI / ENGINEERING / PLATFORMS</span><span>GLOBAL BY DESIGN</span></div></div></Reveal>
  </div>
 </section>
 <section className="section-pad section-intro"><div className="mx-auto max-w-7xl"><Reveal><p className="eyebrow">The company</p><h2 className="section-title mt-3">Technology. Innovation.<br/><span className="gradient-text">Possibility.</span></h2><p className="section-copy">OGE-ACTRA TECH is a technology company building intelligent software and digital platforms across AI, education, commerce, entertainment and emerging digital experiences.</p></Reveal><div className="focus-grid mt-12">{focus.map((item,i)=>{const Icon=item.icon;return <Reveal key={item.title} delay={i*.08}><article className="focus-card"><span className="focus-number">0{i+1}</span><Icon className="text-cyan" size={28}/><h3 className="mt-12 text-2xl font-black">{item.title}</h3><p className="mt-3 max-w-sm leading-7 text-silver">{item.copy}</p><span className="focus-line"/></article></Reveal>})}</div></div></section>
 <section className="section-pad pt-4"><div className="mx-auto max-w-7xl"><Reveal><div className="section-heading-row"><div><p className="eyebrow">Our product ecosystem</p><h2 className="section-title mt-3">Products built for <span className="gradient-text">real-world impact.</span></h2></div><Link href="/products" className="section-link">View all products <ArrowRight size={16}/></Link></div><p className="section-copy">Four products. Four distinct problems. One technology company behind the engineering.</p></Reveal><div className="mt-12 grid gap-6 lg:grid-cols-2">{products.map((p,i)=><ProductCard key={p.slug} product={p} index={i} featured={i===0}/>)}</div></div></section>
 <Ecosystem/>
 <section className="section-pad pt-3"><div className="mx-auto grid max-w-7xl items-stretch gap-8 lg:grid-cols-[.78fr_1.22fr]"><Reveal><div className="flagship-copy h-full"><p className="eyebrow text-purple">Flagship product</p><h2 className="section-title mt-3">Where Artificial Intelligence Meets <span className="gradient-text">Storytelling.</span></h2><p className="section-copy">ACTRA AI is exploring a new approach to filmmaking where creators can create digital characters, build stories, generate scenes, use digital performances, customize fashion and theatrical makeup, license character likeness, monetize digital characters and produce cinematic content.</p><div className="mt-7 flex flex-wrap gap-2">{['AI Filmmaking','Digital Characters','Virtual Production','Creator Economy'].map(x=><span key={x} className="feature-chip">{x}</span>)}</div><Link href="/products/actra-ai" className="btn-primary mt-8 px-7 py-4">Discover ACTRA AI <ArrowRight size={17}/></Link></div></Reveal><Reveal delay={.1}><Link href="/products/actra-ai" className="flagship-image-panel group focus-ring" aria-label="Explore ACTRA AI"><Image src="/products/actra-ai.webp" alt="ACTRA AI cinematic filmmaking product visual" fill sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover transition duration-700 group-hover:scale-[1.035]"/><div className="flagship-image-overlay"/><div className="flagship-corner">ACTRA AI / 001</div><div className="flagship-image-caption"><span>The Future of Film</span><strong>Will Be Generated.</strong></div><div className="flagship-image-cta">Explore <ArrowRight size={16}/></div></Link></Reveal></div></section>
 <section className="section-pad"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><Reveal><p className="eyebrow">Technology</p><h2 className="section-title mt-3">Engineering What <span className="gradient-text">Comes Next.</span></h2></Reveal><Reveal delay={.08}><p className="section-copy mt-0">OGE-ACTRA TECH combines Artificial Intelligence, cloud infrastructure, software engineering, automation, digital platforms, data systems and API-driven architecture into reusable technology capabilities.</p></Reveal></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div className="glass rounded-3xl p-6"><Brain className="text-cyan"/><h3 className="mt-7 font-black">Artificial Intelligence</h3><p className="mt-3 text-sm leading-6 text-silver">Generative AI, intelligent automation, computer vision and language systems.</p></div><div className="glass rounded-3xl p-6"><Layers className="text-cyan"/><h3 className="mt-7 font-black">Platform Engineering</h3><p className="mt-3 text-sm leading-6 text-silver">Scalable web and mobile applications designed around real user behavior.</p></div><div className="glass rounded-3xl p-6"><Database className="text-cyan"/><h3 className="mt-7 font-black">Cloud Infrastructure</h3><p className="mt-3 text-sm leading-6 text-silver">Distributed systems, APIs, databases and cloud services.</p></div><div className="glass rounded-3xl p-6"><Workflow className="text-cyan"/><h3 className="mt-7 font-black">Digital Experiences</h3><p className="mt-3 text-sm leading-6 text-silver">Interactive product experiences designed around how people actually use technology.</p></div></div></div></section>
 <section className="section-pad pt-4"><div className="mx-auto max-w-7xl"><Reveal><p className="eyebrow">Industries we build for</p><h2 className="section-title mt-3">Technology without <span className="gradient-text">one boundary.</span></h2></Reveal><div className="industries mt-10">{industries.map(([name,Icon],i)=>{const I=Icon as typeof Brain;return <Reveal key={name as string} delay={i*.04}><div className="industry flex items-center gap-3"><I size={18} className="text-cyan"/><span>{name as string}</span></div></Reveal>})}</div></div></section>
 <section className="section-pad"><Reveal><div className="vision-panel mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-cyan/15 p-10 text-center md:p-16"><div className="vision-grid"/><p className="eyebrow relative">Our vision</p><h2 className="relative mt-4 text-4xl font-black tracking-tight md:text-6xl">We Don&apos;t Just Build Software.<br/><span className="gradient-text">We Build Possibilities.</span></h2><p className="relative mx-auto mt-6 max-w-2xl text-silver leading-8">Our mission is to transform ambitious ideas into intelligent technology products designed for meaningful scale and global impact.</p><Link href="/company" className="focus-ring relative mt-8 inline-flex items-center gap-2 rounded-full border border-white/15 px-7 py-4 font-bold hover:bg-white/[.06]">Explore the company <ArrowRight size={17}/></Link></div></Reveal></section>
 </>}
